version: '2'
services:
  wp_web_data:
    image: python:2.7-alpine
    volumes:
      - /opt/datastore:/var/www/html

  wp_db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_ROOT_PASSWORD: wp29admin
      MYSQL_PASSWORD: wp29admin
    env_file:
      - ./.env

  wordpress:
    image: wordpress:latest
    depends_on:
      - wp_db
    volumes_from:
      - wp_web_data
    links:
      - wp_db
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wp_db:3306
      WORDPRESS_DB_PASSWORD: wp29admin
      WORDPRESS_DB_PASSWORD: wordpress
    env_file:
      - ./.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    links:
      - wp_db:db
    volumes:
      - /sessions
    ports:
      - "8888:80"
    env_file:
      - ./.env
